### ISSUE TITLE
Correct SD2/SD1 ratio to SD1/SD2 ratio

### ISSUE THREAD

**Issue by clecoued** [Aura-healthcare/hrvanalysis#17]
We have to fix the SD2/SD1 to SD1/SD2 ratio standard measurement

The ratio of SD1/SD2, which measures the unpredictability of the RR time series, is used to measure autonomic balance when the monitoring period is sufficiently long and there is sympathetic activation. SD1/SD2 is correlated with the LF/HF ratio

**Comment by Patil2099** [comment]
@clecoued  Can I work on this?

**Comment by clecoued** [comment]
Sure !

**Comment by clecoued** [comment]
Do not hesitate to ping me or @robinchampseix if you need more informations
