### ISSUE TITLE
Calculating rr-interval list

### ISSUE THREAD

**Issue by loneharoon** [Aura-healthcare/hrvanalysis#20]
Hi Robin,

Do we need to compute the rr_intervals_list from the raw ecg signal or the rr_intervals_list refers to raw signal? I did not get it correctly?

**Comment by robinchampseix** [comment]
Hi,

Thank you for your question. 

It is a **common practise** to remove ectopic beats from the signal. Then you can extract features from those cleand RR-interval (which are also called NN-intervals in the litterature).
[Here](https://aura-healthcare.github.io/hrvanalysis/hrvanalysis.html#module-hrvanalysis.preprocessing) is a link to the API documentation with the reference papers.

Hope that helps :-)
Cheers,
Robin
