### ISSUE TITLE
Calculation of pNN50 wrong?

### ISSUE THREAD

**Issue by skjerns** [Aura-healthcare/hrvanalysis#24]
I'm calculating the pNN50, but it seems like there is a mistake:

```Python
import numpy as np
import hrvanalysis

# create fake NNs, all with >60ms diff
NNs = np.arange(1100, 2000, 60)

pNN50 = hrvanalysis.get_time_domain_features(NNs)['pnni_50']
# should be 100%, but is 93%
```

I also found the reason:

https://github.com/Aura-healthcare/hrvanalysis/blame/2aca66ee65e2bf4867a6badc17322197c196d70d/hrvanalysis/extract_features.py#L109

You take a `np.diff(RR)` and then divide the sum of >50 by `len(RR)`. However, `np.diff(RR)` will have one element less than RR.

To be honest, I'm slightly angry at this really simple mistake. How can I trust this library if even such simple calculations are wrong? I'm using this for scientific calculations, so it would not be good if results were wrong.

**Comment by robinchampseix** [comment]
Hi,

First, I would like to thank you for reporting this problem and using the library.

My understanding from the [main research paper](https://www.escardio.org/static_file/Escardio/Guidelines/Scientific-Statements/guidelines-Heart-Rate-Variability-FT-1996.pdf) might indeed not be correct. But let's have a look at an extract:

<img width="814" alt="Capture d’écran 2020-06-03 à 15 07 53" src="https://user-images.githubusercontent.com/24721898/83640744-db465900-a5ac-11ea-81bb-b795cf17f535.png">

It says clearly that the pNN50 is equal to "NN50 count **_divided by the total number of all NN intervals_**.".

I totally understand your frustration as this is very basic Maths but I tried to strictly follow research papers. I will challenge this with some coworkers who helped me develop the module.

If you like the package though, free to contribute and create pull request :-)
Regards,
Robin

**Comment by robinchampseix** [comment]
Hi again @skjerns ,

After checking with some colleagues, we decided to keep the current implementation.
Two reasons for that:

1. It is not written anywhere that pnn50 could be equal to 1. In the paper, we visually can see that it is never equal to 1 (or 100% as in the screenshot below).

<img width="615" alt="Capture d’écran 2020-06-10 à 09 21 44" src="https://user-images.githubusercontent.com/24721898/84238940-14765000-aafc-11ea-9ab6-59eb68f91a3b.png">


2. We found another quote saying that we should divide by the number of all NN intervals.

<img width="472" alt="Capture d’écran 2020-06-09 à 16 00 28" src="https://user-images.githubusercontent.com/24721898/84239030-31ab1e80-aafc-11ea-9c4d-d81e17f96fb7.png">

Until proven otherwise, the pnn50 will stay as is.

I remind you that this is an Open Source project and we prone kindess and amability. Next time, I would watch your tone (cf: "slightly angry at this really simple mistake") and suggest you dig into some research papers first.

Regards,
Robin

**Comment by skjerns** [comment]
First of all let me apologise for my improper use of language.

Secondly I want to give arguments for adapting the formula to range from 0 to 1. 

Some more recent research papers might use the formula different, however, I think this is a mistake.

In the original research paper that introduced the pNN50 ([Bigger et al 1988](https://doi.org/10.1016/0002-9149(88)90917-4)) the formula is given with 
![Capture](https://user-images.githubusercontent.com/14980558/84755044-797cea80-afc1-11ea-97bc-c9aa3f6e48b0.PNG)


On another note the current implementation will introduce a computational bias.
Assume two analysis, one with 30 second windows, one with 300 second windows and each heart beat off by 60 ms (as in my initial example). This would give a pNN50 of 96.5% for the 30 seconds and 99.7% for 300 second window, although the data stems from the same underlying generator. `pNN50` was exactly introduced to mitigate the bias of absolute counts, and introduce a relative measure. 

Additionally this makes more intuitive sense imo, as a percentage value should naturally range from 0 to 100% and not have an upper limit that is given by the number of beats.

**Comment by skjerns** [comment]
First of all let me apologise for my improper use of language.

Secondly I want to give arguments for adapting the formula to range from 0 to 1. 

Some more recent research papers might use the formula different, however, they might be mistaken in translating the description of the characteristic to a formula. In the original research paper that introduced the pNN50 ([Bigger et al 1988](https://doi.org/10.1016/0002-9149(88)90917-4)) the parameter is described as 
>We computed the absolute value of each individual difference between adjacent N-N intervals and summarized the differences by the percentage of differences exceeding 50ms"
In my understanding this translates to using `n-1` in the denominator, as the "percentage of differences" is taken.

On another note the current implementation will introduce a computational bias.
Assume two analysis, one with 15 second windows, one with 300 second windows and each heart beat off by 60 ms (as in my initial example). This would give a pNN50 of 93.3% for the 30 seconds and 99.7% for 300 second window, although the data stems from the same underlying generator. `pNN50` was exactly introduced to mitigate the bias of absolute values, and to introduce a relative measure. 

It also makes more intuitive sense, as a percentage value should naturally range from 0 to 100% and not have an upper limit that is given by the number of intervals inside the analysis window. 

Additionally, most other HRV analysis tools also use the formula with `n-1` (eg pyHRV, Kubios, ...)

e.g.

```Python
import pyhrv
pyhrv.time_domain.nn50(NNs)
# pNN50 = 100
```

**Comment by lribiere** [comment]
Hi @skjerns, hi Robin,

I agree it's not perfectly clear whether the `pNN50` denominator should be equal to the number of NN intervals (let's say `n`) or the number of pairs of adjacant intervals (`n-1`).

How about allowing both computations and let the user decide ? I'm thinking of a simple boolean parameter for the `get_time_domain_features` function that could give something like this :

```Python
def get_time_domain_features(nn_intervals: List[float], pnni_as_percent: bool = True) -> dict:
# ...
length_int = len(nn_intervals) - 1 if pnni_as_percent else len(nn_intervals)
# ...
pnni_50 = 100 * nni_50 / length_int
# ...
pnni_20 = 100 * nni_50 / length_int
# ...
```
