### ISSUE TITLE
Question of citation

### ISSUE THREAD

**Issue by Kaintels** [Aura-healthcare/hrvanalysis#26]
Hello.

I'm writing a research paper using this library. Are there any citations to quote?

Regards,
Seungwoo

**Comment by robinchampseix** [comment]
Hi Seungwoo,

Thanks for using this library. Do not hesitate to give us your feedback, ask for improvement or create Pull requests if you find a bug :-)

There is a paper which is currently being reviewed. The paper is not available yet as the process takes time.
You can still quote as "A Python Package for heart rate variability analysis and signal preprocessing." Robin Champseix, Laurent Ribière, Clément Lecouedic.

Have a great day,
Robin
